kind: pipeline
name: default

steps:
  - name: Test
    image: python:3.7
    commands:
      - chmod +x ./cc-test-reporter
      - pip install pipenv
      - pipenv install --dev
      - pipenv run pytest